INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (1, 'OP1', 'OP',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (2, 'OP2', 'OP',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (3, 'OP3', 'OP',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (4, 'OP4', 'OP',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (5, 'DI1', 'DI',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (6, 'DI2', 'DI',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (7, 'DI3', 'DI',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (8, 'DI4', 'DI',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (9, 'SU1', 'SU',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (10,'SU2', 'SU',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (11,'SU3', 'SU',1);
INSERT INTO Empleado(id, nombre, cargo,activo)  VALUES (12,'SU4', 'SU',1);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (1,1,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (2,2,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (3,3,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (4,4,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (5,5,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (6,6,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (7,7,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (8,8,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (9,9,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (11,11,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (10,10,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (12,12,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (13,12,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (14,14,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (15,15,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (16,16,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (17,17,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (18,18,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (19,19,0,0);
INSERT INTO Llamada(id, numero_llamada,fue_procesado,duracion_llamada)  VALUES (20,20,0,0);
INSERT INTO Parametro(id, nombre,valor)  VALUES (1,'LIMITE_HILOS',10);
